import './style.css';
import { LabScene } from './lab-scene.js';
import { jointProbabilities, expectedCorrelation } from './physics.js';
import { statistics } from './experiment.js';
import { createMeasurementExport } from './export.js';
import { FloatingPanels } from './panels.js';
import { STAGES } from './stages.js';
import { MeasurementDirector } from './director.js';
import { createMeasurement, MeasurementStore, timestampMatcher } from './measurement.js';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=new Intl.NumberFormat('en-US'), fmt=(v,n=3)=>Number.isFinite(v)?v.toFixed(n):'—';
const saved=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const overrides=saved('entangled-captions-v2',{});
const prefs=saved('entangled-director-v2',{speed:1,hold:0,camera:1.3,pauseAtStages:true,physicsHold:true,safe:false});
let settings={source:'entangled',state:'singlet',visibility:1,a:0,b:0}, timing={sourceRate:1000,delayNs:0,jitterNs:0,windowNs:2};
let store=new MeasurementStore(),pairId=0,run=1,seed=20261003,director,record,scene,busy=false,groupKey=null,lastStage=-1,lastMicro=-1,revealed=2,inspector=null,captionHold=0,captionWait=false,annotationId=null,textOverride=false,lastBatchRecord=null;
document.querySelector('#app').innerHTML=`<main class="laboratory"><div id="scene" aria-label="Interactive optical laboratory. Drag to orbit, right drag to pan, scroll to zoom."></div><div class="vignette"></div><div id="safe-margins" hidden></div><header class="brand"><span>⟡</span><div>ENTANGLED<small>INSIDE A QUANTUM MEASUREMENT</small></div></header><div id="overlays"></div><div id="panel-menu"></div><div id="notice" role="status" hidden></div></main>`;
const panels=new FloatingPanels($('overlays'),{storageKey:'entangled-layout-v2',onChange:({reason})=>{if(reason==='viewport'||reason==='reset-layout')fitDefaultLayout()}}),w=innerWidth,h=innerHeight;
const add=(id,title,content,x,y,width,height,visible=true)=>panels.add({id,title,content,x,y,width,height,visible,dock:id==='transport'?'bottom':'free',collapsed:id==='model'});
add('caption','Chapter / caption',`<div id="chapter-cue" class="eyebrow"></div><h1 id="headline"></h1><p id="caption-text"></p><div id="state-label" class="state-label"></div><div class="buttons"><button id="follow" class="primary">Follow one pair →</button><button id="details-open">Details</button><button id="reveal">Next sentence</button><button id="context-action"></button></div>`,24,86,410,Math.min(540,h-280));
add('transport','Presentation transport',`<div class="transport-row"><button id="previous" title="Previous stage · Left arrow">←</button><button id="play" class="primary">Play</button><button id="next">Next →</button><button id="micro">Micro-step</button><button id="replay">Replay pair</button><button id="fresh">New pair</button><span id="replay-label" class="chip"></span></div><div class="timeline"><input id="scrub" type="range" min="0" max="100" step=".01" value="0" aria-label="Presentation timeline"><div id="stage-markers"></div></div><div class="transport-row secondary"><label>Presentation speed <select id="speed">${[.05,.1,.25,.5,1,2,4,8].map(n=>`<option value="${n}">${n}×</option>`).join('')}</select></label><input id="exact-speed" type="number" min=".01" max="32" step=".05" value="${prefs.speed}" aria-label="Exact presentation speed"><label class="check"><input id="auto" type="checkbox"> Continuous autoplay</label><button id="camera-resume">Resume guided camera</button><button id="director-open">Director controls</button></div>`,Math.max(24,(w-950)/2),h-187,Math.min(950,w-48),166);
add('chapters','Experiment chapters',`<ol class="chapter-list">${STAGES.map((s,i)=>`<li><button data-stage="${i}"><span>${String(i+1).padStart(2,'0')}</span>${esc(s.title)}</button></li>`).join('')}</ol>`,24,86,335,490,false);
add('details','Deeper explanation','<div id="detail-content"></div><div class="buttons"><button id="equation-open">Show equation</button><button id="pbs-test-open">Test this PBS</button></div>',w-445,86,420,490,false);
add('equation','State / equation','<div id="equation-content" class="equation"></div><p class="muted">Angles use local laboratory coordinates. T and R are coherent output paths; a detector creates the record.</p>',w-500,180,470,295,false);
add('settings','Next pair / settings',`<p class="muted">This pair keeps its captured settings. Changes apply to fresh pairs.</p><label>Source <select id="source"><option value="entangled">Entangled singlet</option><option value="classical">Ordinary H/V mixture</option></select></label>${['a','b'].map(a=>`<div class="angle-setting"><label>${a==='a'?'Alice':'Bob'} effective basis <input id="angle-${a}" type="number" min="-180" max="180" step=".5" value="0">°</label><input id="range-${a}" type="range" min="-90" max="90" step=".5" value="0" aria-label="${a==='a'?'Alice':'Bob'} analyzer angle"><div id="hwp-${a}" class="muted">HWP fast axis 0°</div></div>`).join('')}<div class="buttons"><button data-bases="0,0">H/V · H/V</button><button data-bases="45,45">D/A · D/A</button><button data-bases="0,45">H/V · D/A</button></div><button id="apply-fresh" class="primary">Apply & follow a fresh pair</button><label>Simulated source rate <input id="source-rate" type="number" min="1" max="1000000" value="1000"> pairs/s</label><details><summary>Time-tagger settings</summary><label>Bob readout delay Δ₀ <input id="delay" type="number" step=".1" value="0"> ns</label><label>Independent timestamp jitter σ <input id="jitter" type="number" min="0" step=".1" value="0"> ns</label><label>Coincidence full width W <input id="window" type="number" min=".01" step=".1" value="2"> ns</label><p class="muted">|Δt − Δ₀| ≤ W/2. Timing never changes polarization probabilities.</p></details>`,w-355,86,330,515,false);
add('statistics','Fresh pairs / live totals',`<div class="stat-heading"><strong id="total">0</strong><span>COMPLETED PAIRS<br>Live totals · replay adds no counts</span></div><label>Count group <select id="group-select"></select></label><div id="bins"></div><div id="correlation"></div><div class="batch-buttons">${[100,1000,10000,100000].map(n=>`<button data-batch="${n}">+ ${nf.format(n)}</button>`).join('')}</div><div id="batch-status" class="muted">Every pair is freshly sampled. Inspect an actual sampled pair after the batch.</div><p class="muted">One H/V run alone does not demonstrate entanglement. Compare fresh runs at different bases.</p><div class="buttons"><button id="settings-open">Change bases</button><button id="record-open">Detector records</button><button id="inspect-batch" disabled>Inspect a pair from the batch</button><button id="export">Export records</button><button id="reset-experiment">Reset experiment</button></div>`,w-390,86,365,535,false);
add('records','Detections / time tagger','<div id="pair-result"></div><div id="timing-results"></div><div id="histogram"></div><div id="event-log"></div>',w-455,86,430,545,false);
add('director','Caption / camera direction',`<label>Stage headline <input id="edit-headline" type="text"></label><label>Stage caption <textarea id="edit-caption" rows="4"></textarea></label><div class="buttons"><button id="save-caption" class="primary">Save text</button><button id="restore-caption">Restore default text</button><button id="show-caption">Show all text</button><button id="hide-caption-text">Hide text</button></div><label>Stage hold <input id="hold-time" type="number" min="0" max="120" step=".5" value="${prefs.hold}"> seconds</label><label class="check"><input id="wait-next" type="checkbox"> Wait for my Next click</label><label class="check"><input id="physics-hold" type="checkbox"> Pause physics at the teaching beat</label><label class="check"><input id="loop" type="checkbox"> Loop current stage (same pair)</label><label>Camera transition <input id="camera-time" type="number" min="0" max="10" step=".1" value="${prefs.camera}"> seconds</label><label class="check"><input id="safe" type="checkbox"> Recording-safe margins</label><label class="check"><input id="reduced" type="checkbox"> Reduced motion</label><button id="fullscreen">Fullscreen presentation</button><p class="muted">Space: play/pause · ←/→: stages · H: hide/restore overlays · Escape: leave the inspector. Shortcuts pause while you type.</p>`,w-445,86,420,565,false);
add('camera','Camera / exploration',`<div class="camera-grid">${[['overview','Overview'],['source','Source'],['hwp','HWP'],['inside-pbs','Inside PBS'],['detector','Detector'],['time-tagger','Time tagger']].map(([id,t])=>`<button data-camera="${id}">${t}</button>`).join('')}</div><p id="camera-mode" class="muted">Guided camera. Orbit to take control.</p><button id="second-arm">Second-arm inset</button><p class="muted">Drag: orbit · right drag: pan · wheel: zoom. Click hardware to inspect it.</p>`,24,440,325,270,false);
add('map','Apparatus orientation',`<svg class="mini-map" viewBox="0 0 380 155" aria-label="Source splits into Alice and Bob, each HWP and PBS routes to two SPADs"><path d="M35 77H85V30H270M85 77V122H270M235 30V6H315M235 122V149H315" fill="none" stroke="#77cfff" stroke-width="3"/><circle cx="35" cy="77" r="12" fill="#b09bff"/><g fill="#cfe8ff" font-size="15"><text x="6" y="106">Source</text><text x="103" y="22">Alice · HWP → PBS</text><text x="103" y="114">Bob · HWP → PBS</text><text x="278" y="35">A+</text><text x="322" y="12">A−</text><text x="278" y="128">B+</text><text x="322" y="151">B−</text></g></svg><p class="muted">Cyan: Alice · violet: Bob. Colors identify arms, not energies.</p>`,24,440,390,255,false);
add('inset','Bob / second-arm view','<div id="second-arm-view"></div><p class="muted">Same physical timeline, second camera.</p>',w-380,86,350,280,false);
add('annotation','Component annotation','<div id="annotation-content"></div><label class="check"><input id="leader-toggle" type="checkbox"> Leader line</label>',w-365,86,340,275,false);
add('pbs-test','Isolated PBS component test',`<p>Prepared input in a separate component experiment. It never feeds the pair counts.</p><div class="buttons"><button data-test-pbs="H">H input</button><button data-test-pbs="V">V input</button><button data-test-pbs="D">D input</button></div><div id="pbs-test-state" class="state-label"></div><p class="muted">H transmits; V reflects; D has coherent amplitudes in both output modes. An unmeasured singlet member is I/2, not pure D.</p><button id="close-test" class="primary">Return to the paused pair</button>`,24,86,405,350,false);
add('model','Quantum-model simulation','<p>Ideal singlet · lossless HWP/PBS · perfect single-photon detection.</p><p class="muted">Wavepackets, coating fields and carriers are explanatory schematics. Presentation time is independent of nanosecond model time.</p><div class="legend"><span>Alice ━ cyan</span><span>Bob ━ violet</span><span>Branches = amplitudes</span></div>',w-380,70,355,220,true);
$('panel-menu').append(panels.menuElement());const captionActions=panels.get('caption').querySelector('.buttons');$('chapter-cue').after(captionActions);
function fitDefaultLayout(){const layout=panels.snapshot(),c=layout.panels.caption;if(c&&!c.manualPosition&&!c.locked){const target=Math.max(250,Math.min(540,innerHeight-280));if(c.height!==target){c.height=target;panels.restore(layout)}}}
function notify(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('notice').hidden=true,4500)}
function savePrefs(){localStorage.setItem('entangled-director-v2',JSON.stringify(prefs))}
function shouldWait(d){return prefs.pauseAtStages&&(d.waitForNext??true)}
function caption(index){return {...STAGES[index],...overrides[STAGES[index].id]}}
function groups(){return [...store.groups.values()]}
function dataset(){return groups().find(g=>g.key===groupKey)??groups().at(-1)??{settings:record?.settings??settings,total:0,counts:{'++':0,'+-':0,'-+':0,'--':0},records:[],events:[]}}
const analysisCache=new WeakMap();
function fresh({play=false}={}){
 if(inspector)closeInspector();record=createMeasurement(settings,{...timing,seed:seed+pairId,id:++pairId,runId:`run-${run}`});
 director=new MeasurementDirector(record,{onCommit:r=>{store.commit(r);refreshStats()}});director.speed=prefs.speed;director.pauseAtStages=prefs.pauseAtStages&&prefs.physicsHold;
 lastStage=-1;lastMicro=-1;revealed=2;captionHold=0;play?director.play():director.pause();
 scene?.setAnalyzerAngles(record.settings.a,record.settings.b);scene?.setSource(record.settings.source);$('scrub').max=director.state.duration;$('loop').checked=false;updateView(true);refreshStats();
}
function closeInspector(){if(!inspector)return;scene.closePBSInspector();director.seek(inspector.time);director.pause();inspector=null;panels.hide('pbs-test');updateView(true)}
function updateView(force=false,captionIndex=null){
 if(!director)return;const s=director.state;if(!inspector)scene?.setTimelineState({...s,record});
 const index=captionIndex??(!prefs.physicsHold&&(captionHold>0||captionWait)&&lastStage>=0?lastStage:s.stageIndex);const changed=index!==lastStage,d=caption(index);
 if(changed||force){$('chapter-cue').textContent=`${String(index+1).padStart(2,'0')} / 10 · ${d.title}`;$('headline').textContent=d.headline;revealed=1;textOverride=false;
 $('detail-content').innerHTML=`<h2>${esc(d.title)}</h2>${String(d.details??'').split('\n').filter(Boolean).map(t=>`<p>${esc(t)}</p>`).join('')}`;
 $('equation-content').textContent=d.equation??'P(s,t | a,b) = [1 − st cos 2(a−b)] / 4';
 if(index===6)$('detail-content').innerHTML+='<p>The glass window sits above the cyan p region, violet depletion / high-field layer and blue n region. Carriers multiply in the field; the resistor, readout circuit and quench indicator show the electrical response. Device dimensions and carrier counts are enlarged schematics.</p>';if(record.settings.source==='classical'&&index===1){$('equation-content').textContent='ρmix = (|HV⟩⟨HV| + |VH⟩⟨VH|)/2';$('detail-content').innerHTML='<h2>Ordinary correlated source</h2><p>This separable density mixture has the same local I/2 marginals as the singlet. It lacks the coherent relative phase between H/V and V/H alternatives, so its correlations differ at rotated bases.</p>'}if(record.settings.source==='classical'&&index===5){$('equation-content').textContent='ρout = (VAUA ⊗ VBUB) ρmix (VAUA ⊗ VBUB)†';$('detail-content').innerHTML+='<p>For the ordinary source, the full output is a density mixture. The local lossless isometry preserves each component’s amplitudes; it does not create singlet coherence between the mixture alternatives.</p>'}$('edit-headline').value=d.headline;$('edit-caption').value=(d.captions??[d.caption??'']).join('\n');$('hold-time').value=d.hold??prefs.hold;$('wait-next').checked=shouldWait(d);
 document.querySelectorAll('[data-stage]').forEach(b=>b.classList.toggle('active',+b.dataset.stage===index));captionHold=+(d.hold??prefs.hold);captionWait=!prefs.physicsHold&&(shouldWait(d));director.pauseAtStages=(shouldWait(d))&&prefs.physicsHold;lastStage=index;}
 let texts=d.captions??[d.caption??''];
 if(record.settings.source==='classical'&&s.stageIndex===1)texts=['This source prepares a statistical H/V–V/H mixture, without the singlet’s coherent relative phase.'];
 if(index===5&&record.settings.source==='classical')texts=['Each component follows the same ideal local optics. The H/V ensemble remains a statistical mixture of joint alternatives.'];if(index===7&&record.settings.source==='classical')texts=['This separable mixture gives one joint result. Its correlation is −cos(2a) cos(2b); diagonal bases do not guarantee opposite outputs.'];
 if(index===7&&record.settings.source!=='classical'&&Math.abs(Math.sin((record.settings.a-record.settings.b)*Math.PI/180))>1e-10)texts=['The outputs form one jointly sampled result. At different bases, opposite outcomes are no longer guaranteed.'];
 $('caption-text').textContent=texts.slice(0,revealed).join(' ');if(!textOverride&&index===6&&s.stageIndex===6&&s.detectionsVisible)revealed=Math.max(revealed,2);if(!textOverride&&index===9&&s.stageProgress>.6)revealed=Math.max(revealed,2);$('state-label').textContent=`${index!==s.stageIndex?'Caption held · live timeline: ':''}${record.settings.source==='classical'&&s.phase==='coherent-polarization-path'?'Polarization-and-path density mixture':s.stateLabel??'Joint polarization state'}${s.microLabel?' · '+s.microLabel:''}`;
 $('loop').checked=s.loopStage!==null;$('play').textContent=s.paused?'Play':'Pause';$('scrub').value=s.time;$('replay-label').textContent=s.replay?'REPLAY · SAME PAIR':`PAIR ${record.id} · ${record.settings.a}° / ${record.settings.b}°`;
 $('context-action').textContent=s.stageIndex===4||s.stageIndex===5?'Test this PBS':s.stageIndex===3?'Measurement settings':s.stageIndex>=8?'Collect fresh pairs':s.stageIndex>=6?'Detector records':'Explore cameras';$('follow').hidden=s.time>0;$('camera-mode').textContent=scene?.guidedCamera?'Guided camera. Orbit to take control.':'Manual camera. Resume guidance when ready.';
 if(changed||s.microIndex!==lastMicro||force){refreshRecords();lastMicro=s.microIndex}
}
function analyze(d){
 const old=analysisCache.get(d);if(old?.total===d.total)return old;
 const records=d.records??[],captured=records[0]?.timing??timing;
 const matched=timestampMatcher(d.events??records.flatMap(r=>r.events),{delayNs:captured.delayNs,windowNs:captured.windowNs});
 const counts={'++':0,'+-':0,'-+':0,'--':0};for(const m of matched.matches)counts[m.outcomeKey]++;
 const value={total:d.total,captured,matched,observed:{settings:d.settings,total:matched.matches.length,counts}};analysisCache.set(d,value);return value;
}
function refreshStats(){const d=dataset(),analysis=analyze(d),o=statistics(analysis.observed),p=jointProbabilities(d.settings);$('total').textContent=nf.format(d.total);
 $('group-select').innerHTML=groups().length?groups().map((g,i)=>`<option value="${esc(g.key??i)}" ${g===d?'selected':''}>${esc(g.runId)} · ${g.settings.a}° / ${g.settings.b}° · ${g.settings.source==='classical'?'mixture':'singlet'} · ${nf.format(g.total)}</option>`).join(''):'<option>No completed pairs</option>';
 $('bins').innerHTML=['++','+-','-+','--'].map(k=>`<div class="bin"><span>${k.replaceAll('-','−')}</span><div class="bar-track"><i style="width:${o.n?100*analysis.observed.counts[k]/o.n:0}%"></i><b style="left:${100*p[k]}%" title="Theory"></b></div><strong>${nf.format(analysis.observed.counts[k])}</strong><small>${o.n?fmt(100*analysis.observed.counts[k]/o.n,1)+'%':'—'} <em>/ ${fmt(100*p[k],1)}% theory</em></small></div>`).join('');
 $('correlation').innerHTML=`<div class="correlation"><span>${nf.format(o.n)} matched · E<strong>${fmt(o.e)}</strong></span><span>Exact theory<strong>${fmt(expectedCorrelation(d.settings))}</strong></span></div><div class="muted">Alice + ${o.n?fmt(100*o.aPlus,1)+'%':'—'} · Bob + ${o.n?fmt(100*o.bPlus,1)+'%':'—'} · local theory 50%</div>`;refreshRecords()}
function histBars(matches,captured=timing){const bins=Array(17).fill(0),span=Math.max(2,captured.windowNs,6*captured.jitterNs);for(const m of matches){const dt=m.deltaNs??m.dt??m.deltaTimeNs??0,i=Math.round(8+8*(dt-captured.delayNs)/span);if(i>=0&&i<17)bins[i]++}const max=Math.max(1,...bins);return bins.map((n,i)=>`<i style="height:${100*n/max}%" title="${fmt(captured.delayNs+(i-8)*span/8,2)} ns · ${n}"></i>`).join('')}
function refreshRecords(){if(!director)return;const s=director.state,visible=s.jointOutcomeVisible;
 $('pair-result').innerHTML=visible?`<div class="result-card"><span>PAIR ${record.id} · ${esc(record.runId)}</span><strong>${esc(record.detectors.a)} & ${esc(record.detectors.b)}</strong><p>Captured bases ${record.settings.a}° / ${record.settings.b}°. Incoming basis ${alias(record.settings.a)} / ${alias(record.settings.b)}. Physical ports H(T) / V(R).</p></div>`:'<div class="state-label">No detector record revealed before absorption.</div>';
 $('timing-results').innerHTML=visible?(record.events??[]).map(e=>`<div class="event-row"><strong>${esc(e.detector)}</strong><span>Absorption ${fmt(e.modelDetectionTimeNs??record.modelDetectionTimesNs?.[e.arm.toLowerCase()])} ns<br>Readout ${s.readoutsVisible.includes(e.arm)?fmt(e.timestampNs)+' ns':'pending pulse / time tagger'}</span></div>`).join(''):'<p class="muted">The passive PBS routes coherent amplitudes. No detector result yet.</p>';
 const d=dataset(),records=d.records??[],{captured,matched}=analyze(d),matches=matched.matches;
 $('histogram').innerHTML=`<div class="hist-title">Timestamp matching · ${nf.format(matches.length)} coincidences</div><div class="delta-hist">${histBars(matches,captured)}</div><p class="muted">Δt=tB−tA · σ=0 gives a sharp peak. A timing peak alone is not evidence of entanglement. Full width W=${captured.windowNs} ns. ${matched.ambiguous.length} ambiguous, ${matched.unmatchedA.length+matched.unmatchedB.length} unmatched events; totals include every pair.</p>`;
 $('event-log').innerHTML=`<h3>Recent committed records <small>(live totals)</small></h3>${records.slice(-8).reverse().map(r=>`<div class="log-row"><span>#${r.id}</span><strong>${r.detectors.a} ${r.detectors.b}</strong><span>${fmt(r.events[0].timestampNs,2)} ns</span></div>`).join('')||'<p class="muted">No committed pairs yet.</p>'}`}
function alias(a){return a%180===0?'H/V':a%180===45?'D/A':`${a}° ±`}
scene=new LabScene($('scene'),{onInspect:i=>{annotationId=i.id;$('annotation-content').innerHTML=`<h2>${esc(i.title)}</h2><p>${esc(i.description)}</p>`;panels.show('annotation');const point=scene.projectComponent?.(i.id);if(point)panels.setAnchor('annotation',point,{leaderLine:$('leader-toggle').checked})},onCameraOverride:()=>updateView()});
scene.setCameraTransition(prefs.camera);fresh();if(!panels.get('inset').hidden)scene.setSecondArmInset($('second-arm-view'));$('stage-markers').innerHTML=STAGES.map((s,i)=>`<button data-stage="${i}" title="${esc(s.title)}" style="left:${100*director.starts[i]/director.duration}%">${i+1}</button>`).join('');
$('speed').value=prefs.speed;$('auto').checked=!prefs.pauseAtStages;$('physics-hold').checked=prefs.physicsHold;$('safe').checked=prefs.safe;$('safe-margins').hidden=!prefs.safe;
function goStage(i){closeInspector();director.goToStage(Math.max(0,Math.min(9,i)));updateView(true,director.state.stageIndex)}
function playPause(){if(inspector)return;director.state.paused?director.play():director.pause();updateView()}
$('context-action').onclick=()=>{const i=director.state.stageIndex;if(i===4||i===5)$('pbs-test-open').click();else panels.show(i===3?'settings':i>=8?'statistics':i>=6?'records':'camera')};
$('follow').onclick=()=>{director.play();updateView()};$('play').onclick=playPause;$('next').onclick=()=>{closeInspector();if(!prefs.physicsHold&&lastStage<director.state.stageIndex){captionHold=0;captionWait=false;updateView(true,Math.min(9,lastStage+1))}else{captionHold=0;captionWait=false;director.nextStage();updateView(true,director.state.stageIndex)}};$('previous').onclick=()=>goStage(director.state.stageIndex-1);
$('micro').onclick=()=>{if(!inspector){director.microStep();updateView()}};$('replay').onclick=()=>{closeInspector();director.replay();lastStage=-1;updateView(true)};$('fresh').onclick=()=>fresh();
$('scrub').oninput=()=>{closeInspector();director.pause();director.seek(+$('scrub').value);updateView()};$('camera-resume').onclick=()=>{scene.resumeGuidedCamera();updateView()};
function playback(){director.pauseAtStages=shouldWait(caption(lastStage))&&prefs.physicsHold;$('auto').checked=!prefs.pauseAtStages;savePrefs();updateView(true,lastStage)}
$('auto').onchange=()=>{prefs.pauseAtStages=!$('auto').checked;playback()};$('wait-next').onchange=()=>{const id=STAGES[lastStage].id;overrides[id]={...overrides[id],waitForNext:$('wait-next').checked};if($('wait-next').checked)prefs.pauseAtStages=true;localStorage.setItem('entangled-captions-v2',JSON.stringify(overrides));playback()};$('physics-hold').onchange=()=>{prefs.physicsHold=$('physics-hold').checked;playback()};
function speed(v){if(!Number.isFinite(v))return;prefs.speed=Math.max(.01,Math.min(32,v));director.speed=prefs.speed;$('exact-speed').value=prefs.speed;savePrefs()}
$('speed').onchange=()=>speed(+$('speed').value);$('exact-speed').onchange=()=>speed(+$('exact-speed').value);
for(const[b,p]of[['details-open','details'],['director-open','director'],['equation-open','equation'],['settings-open','settings'],['record-open','records']])$(b).onclick=()=>panels.show(p);
$('reveal').onclick=()=>{textOverride=true;revealed++;updateView()};$('show-caption').onclick=()=>{textOverride=true;revealed=10;panels.show('caption');updateView()};$('hide-caption-text').onclick=()=>{textOverride=true;revealed=0;updateView()};
$('save-caption').onclick=()=>{overrides[STAGES[lastStage].id]={headline:$('edit-headline').value,captions:$('edit-caption').value.split('\n').filter(Boolean),hold:+$('hold-time').value,waitForNext:$('wait-next').checked};localStorage.setItem('entangled-captions-v2',JSON.stringify(overrides));updateView(true);notify('Caption saved.')};
$('restore-caption').onclick=()=>{delete overrides[STAGES[lastStage].id];localStorage.setItem('entangled-captions-v2',JSON.stringify(overrides));updateView(true)};
$('hold-time').onchange=()=>{prefs.hold=Math.max(0,+$('hold-time').value);captionHold=prefs.hold;savePrefs()};$('loop').onchange=()=>director.setLoopCurrentStage($('loop').checked);$('camera-time').onchange=()=>{prefs.camera=Math.max(0,+$('camera-time').value);scene.setCameraTransition(prefs.camera);savePrefs()};$('safe').onchange=()=>{prefs.safe=$('safe').checked;$('safe-margins').hidden=!prefs.safe;savePrefs()};$('reduced').onchange=()=>scene.setReducedMotion($('reduced').checked);
$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.().catch(()=>notify('Fullscreen was not allowed by this browser.'));
function queue(){const a=+$('angle-a').value,b=+$('angle-b').value;if(!Number.isFinite(a)||!Number.isFinite(b))return;settings={...settings,a,b,source:$('source').value};for(const arm of['a','b']){$('range-'+arm).value=settings[arm];$('hwp-'+arm).textContent=`HWP fast axis ${fmt(settings[arm]/2,1)}° · fixed PBS`}run++;groupKey=null}
for(const arm of['a','b']){$('angle-'+arm).onchange=queue;$('range-'+arm).oninput=()=>{$('angle-'+arm).value=$('range-'+arm).value;queue()}}$('source').onchange=queue;$('apply-fresh').onclick=()=>{queue();fresh({play:true})};
for(const[id,key]of[['source-rate','sourceRate'],['delay','delayNs'],['jitter','jitterNs'],['window','windowNs']])$(id).onchange=()=>{const v=+$(id).value;if(Number.isFinite(v)&&(key==='delayNs'||v>0||(key==='jitterNs'&&v===0))){timing[key]=v;run++;refreshRecords()}};
$('group-select').onchange=()=>{groupKey=$('group-select').value;refreshStats()};
$('pbs-test-open').onclick=()=>{if(!inspector){inspector={time:director.state.time};director.pause()}panels.show('pbs-test');scene.testPBS('D');$('pbs-test-state').textContent='D → (|H,T⟩ + |V,R⟩)/√2 · coherent component test';updateView()};$('close-test').onclick=closeInspector;
$('second-arm').onclick=()=>{panels.show('inset');scene.setSecondArmInset?.($('second-arm-view'))};$('leader-toggle').onchange=()=>{const point=scene.projectComponent?.(annotationId);if(point)panels.setAnchor('annotation',point,{leaderLine:$('leader-toggle').checked})};
$('reset-experiment').onclick=()=>{lastBatchRecord=null;$('inspect-batch').disabled=true;job++;busy=false;document.querySelectorAll('[data-batch]').forEach(b=>b.disabled=false);store=new MeasurementStore();run++;pairId=0;groupKey=null;fresh();notify('Experiment reset. Panel layout preserved.')};
$('inspect-batch').onclick=()=>{if(!lastBatchRecord)return;closeInspector();record=lastBatchRecord;director=new MeasurementDirector(record,{onCommit:r=>{store.commit(r);refreshStats()}});director.speed=prefs.speed;director.replay();lastStage=-1;lastMicro=-1;captionWait=false;captionHold=0;scene.setAnalyzerAngles(record.settings.a,record.settings.b);scene.setSource(record.settings.source);$('scrub').max=director.duration;updateView(true);notify('Inspecting the same sampled batch record. Live totals are unchanged.');};
let job=0;const worker=new Worker(new URL('./measurement-worker.js',import.meta.url),{type:'module'});
worker.onmessage=async({data})=>{if(data.id!==job)return;if(data.progress!==undefined){$('batch-status').textContent=`Sampling fresh pairs · ${nf.format(data.progress)}`;return}if(data.error){busy=false;document.querySelectorAll('[data-batch]').forEach(b=>b.disabled=false)}if(data.error){notify(data.error);return}lastBatchRecord=data.result.records[0];$('inspect-batch').disabled=false;const epoch=job;for(let i=0;i<data.result.records.length;i+=2000){if(job!==epoch)return;store.commitBatch({records:data.result.records.slice(i,i+2000)});if((i+2000)%20000===0){groupKey=null;refreshStats()}$('batch-status').textContent=`Recording ${nf.format(Math.min(i+2000,data.result.records.length))} fresh pairs…`;await new Promise(requestAnimationFrame)}busy=false;document.querySelectorAll('[data-batch]').forEach(b=>b.disabled=false);groupKey=null;refreshStats();$('batch-status').textContent=`${nf.format(data.result.total??data.result.records.length)} fresh pairs recorded · ${fmt(data.elapsedMs/1000,2)} s worker computation · no per-pair meshes.`};
worker.onerror=e=>{busy=false;document.querySelectorAll('[data-batch]').forEach(b=>b.disabled=false);notify('Batch worker: '+e.message)};
function batch(count){if(busy)return;busy=true;panels.show('statistics');document.querySelectorAll('[data-batch]').forEach(b=>b.disabled=true);$('batch-status').textContent=`Sampling ${nf.format(count)} fresh pairs in the worker…`;const startId=pairId+1;pairId+=count;worker.postMessage({id:++job,count,settings:{...settings},seed:seed+startId,startId,runId:`run-${run}`,timing:{...timing}})}
$('export').onclick=()=>{const data=createMeasurementExport({store,seed,timing,captionOverrides:overrides,layout:panels.snapshot()});const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='entangled-measurements.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.stage!==undefined)goStage(+b.dataset.stage);if(b.dataset.bases){const[a,bv]=b.dataset.bases.split(',').map(Number);$('angle-a').value=a;$('angle-b').value=bv;queue()}if(b.dataset.camera)scene.setCameraPreset(b.dataset.camera);if(b.dataset.testPbs){scene.testPBS(b.dataset.testPbs);$('pbs-test-state').textContent={H:'H → |H,T⟩',V:'V → |V,R⟩',D:'D → (|H,T⟩ + |V,R⟩)/√2'}[b.dataset.testPbs]}if(b.dataset.batch)batch(+b.dataset.batch)});
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]'))return;if(e.code==='Space'&&!e.target.closest('button,a')){e.preventDefault();playPause()}if(e.key==='ArrowRight'){e.preventDefault();goStage(director.state.stageIndex+1)}if(e.key==='ArrowLeft'){e.preventDefault();goStage(director.state.stageIndex-1)}if(e.key.toLowerCase()==='h')panels.toggleAll();if(e.key==='Escape'){if(inspector)closeInspector();else scene.setCameraPreset('overview')}});
let prev=performance.now();function frame(now){const dt=Math.min(.1,(now-prev)/1000);prev=now;if(director&&!inspector){const before=director.state,d=caption(before.stageIndex);if(!before.paused){if(captionHold>0&&prefs.physicsHold)captionHold=Math.max(0,captionHold-dt);else{if(!prefs.physicsHold)captionHold=Math.max(0,captionHold-dt);director.update(dt)}if((shouldWait(d))&&prefs.physicsHold&&director.state.stageIndex!==before.stageIndex)director.pause()}updateView();if(annotationId){const point=scene.projectComponent?.(annotationId);if(point)panels.setAnchor('annotation',point,{leaderLine:$('leader-toggle').checked})}}requestAnimationFrame(frame)}requestAnimationFrame(frame);
