/** Editable presentation defaults. Targets and cutaways refer to the same apparatus. */
const definitions = [
  ['apparatus', 'The apparatus', 'One pair. Two measurement stations.', ['One photon goes to Alice and one to Bob. Each station has two possible detector outputs.'], 'The source, two HWPs, two passive PBS cubes, four SPADs and four time-tagger channels form one experiment.', '', 'whole', 'none', ['Trace Alice’s route', 'Trace Bob’s route', 'Four detector outputs']],
  ['source', 'Prepare a pair', 'Two photons. One joint quantum state.', ['The source prepares an entangled pair. It does not hand each photon a predetermined H/V label.'], 'We model the state after successful pair generation. The source interior is a schematic; source efficiency and microscopic nonlinear conversion are not calculated.', '|ψ⁻⟩ = (|HV⟩ − |VH⟩)/√2', 'source', 'source', ['Pump schematic', 'One coherent joint state', 'Pair prepared']],
  ['paths', 'Separate paths', 'Separated in space, described together.', ['Before detection, the pair evolves as a joint quantum state. Either side alone gives random polarization outcomes.'], 'Each local polarization state is I/2. Wavepackets show amplitudes, not balls with hidden polarization arrows or a physical signal between arms.', 'ρA = ρB = I/2', 'arms', 'none', ['Leave the source', 'Separate optical arms', 'One joint description']],
  ['basis', 'Choose the basis', 'Choose the basis, not the outcome.', ['The wave plate changes which polarization basis the fixed PBS analyzes. It does not force a chosen detector to click.'], 'Fast and slow axes differ by π phase at the design wavelength. Analyzer 45° uses HWP fast axis 22.5°. Settings are captured for this pair; new choices apply to a fresh pair.', 'U(θ) = [[cos 2θ, sin 2θ], [sin 2θ, −cos 2θ]]; θ = a/2', 'hwp', 'hwp', ['Optical axes', 'Relative phase π', 'Effective analysis basis']],
  ['pbs', 'Inside the PBS', 'A passive interface separates the components.', ['The coating transmits one polarization component and reflects the orthogonal component. No electronics or decision-making is involved.'], 'Two right-angle prisms meet at a dielectric coating. In this local convention H/p transmits and V/s reflects. Exaggerated coating layers illustrate interference; no Maxwell solver or real coating recipe is claimed.', '|H,in⟩ → |H,T⟩; |V,in⟩ → |V,R⟩', 'pbs', 'pbs', ['Transparent housing', 'Separate the prism halves', 'Coated interface', 'Transmit H/p', 'Reflect V/s']],
  ['branches', 'Before detection', 'Separated paths. No recorded result yet.', ['The ideal PBS coherently links polarization to output path. A detector has not yet recorded an outcome.'], 'The full polarization-and-path state remains coherent. Ignoring path can hide that coherence in the polarization-only description. Two branches are single-photon amplitudes, never two half-energy photons.', '(|H,T⟩A|V,R⟩B − |V,R⟩A|H,T⟩B)/√2 at a = b = 0°', 'branches', 'pbs', ['Coherent transmitted amplitude', 'Coherent reflected amplitude', 'No irreversible record']],
  ['detector', 'Inside the first detector', 'A photon becomes a detector record.', ['Absorption triggers an avalanche. The electrical pulse identifies which output registered the photon.', 'This is a destructive measurement. We keep the result, not the original two-photon entangled state.'], 'Above-breakdown field, carriers, impact ionization, quenching and recovery are enlarged explanatory schematics. Absorption and irreversible amplification are the measurement interaction; later LEDs, sound and observers do not cause it.', 'Photon absorption → carriers → avalanche → pulse → quench', 'detector', 'detector', ['Photon absorption creates carriers', 'High field accelerates carriers', 'Impact ionization: avalanche', 'Electrical pulse', 'Quench and recovery']],
  ['partner', 'The joint outcome', 'One pair gives one joint outcome.', ['At matching bases, this ideal singlet gives opposite outcomes. Which side gets which outcome is random.'], 'The partner outcome belongs to the same joint event. Camera order is storytelling order, not physical measurement order. If both absorptions occurred at the inspected model time, both are marked detected.', 'P(s,t|a,b) = [1 − st cos 2(a−b)]/4', 'partner', 'detector', ['Inspect partner’s recorded outcome', 'Combine the two outcomes', 'Photons absorbed; records retained']],
  ['timing', 'Pulses and timestamps', 'Match the detections, then compare the outcomes.', ['The time tagger records when each detector fired. Nearby detections, after accounting for delay, can be paired for analysis.'], 'W is the total coincidence-window width. Matching uses timestamps and observed channels, not simulator emission IDs. Delay is optical/electronic timing; a coincidence peak alone does not establish entanglement.', '|(tB − tA) − Δ0| ≤ W/2', 'electronics', 'electronics', ['Pulse edges enter four channels', 'Readout timestamps', 'Calibrate the delay', 'Candidate time-window match', 'Commit the completed result']],
  ['pattern', 'From one event to a pattern', 'The photons are gone. The pattern remains.', ['Each pair is measured once. Repeating the experiment reveals the correlation between the recorded outcomes.', 'Matching H/V outcomes alone cannot prove entanglement. Correlations across different bases provide a stronger test.'], 'Fresh pairs populate separate run/settings groups. Theory and finite observations are distinct. Displayed wavepackets are representative examples, not the requested sample size or an experimental proof.', 'E = (N++ + N−− − N+− − N−+)/N', 'whole', 'none', ['One event enters a count bin', 'Repeat with fresh pairs', 'Compare separate measurement runs']],
];

export const STAGES = Object.freeze(definitions.map((definition, index) => {
  const [id, title, headline, captions, details, equation, target, cutaway, labels] = definition;
  const at = index === 6 ? [0.12, 0.28, 0.45, 0.65, 0.84]
    : index === 8 ? [0.08, 0.30, 0.50, 0.72, 1]
      : labels.map((_, i) => i / Math.max(1, labels.length - 1));
  return Object.freeze({ id, title, headline, captions: Object.freeze(captions), caption: captions[0], details, equation, target,
    cameraBookmark: target, cutaway, duration: [4, 6, 8].includes(index) ? 10 : 8,
    pausePoint: true, microEvents: Object.freeze(labels.map((label, i) => Object.freeze({ id: `${id}-${i + 1}`, label, at: at[i] }))),
  });
}));

export function stageCaption(stage, settings) {
  if (stage.id === 'partner' && Math.abs(Math.sin((settings.a - settings.b) * Math.PI / 180)) > 1e-10) {
    return 'This joint outcome is sampled in the selected bases. With different bases, opposite results are not guaranteed.';
  }
  return stage.caption;
}
